### ISSUE TITLE
Telas 

### ISSUE THREAD

**Issue by rayanesal** [Rayaninha/AgroVen#18]
Desenvolvimento das Telas do projeto!

- [x] Escolher uma ferramenta;
- [x] Escolher linguagens;
- [x] Escolher um _framework_ de desenvolvimento;
- [x] Prototipar graficamente a tela no Figma;
- [x] "Codar" a Tela;

**Comment by Luanjoss** [comment]
https://www.figma.com/team_invite/redeem/uE4XhwyXMzzkDzSximwic0

Protótipos gráfico das telas no Figma.
