### ISSUE TITLE
Modelo de Banco de dados

### ISSUE THREAD

**Issue by srtaduda** [Rayaninha/AgroVen#2]
- [x] Elaborar Modelo Entidade Relacionamento #4 
- [x] Elaborar Modelo Lógico #22 
- [x] Gerar script do Modelo Físico
