### ISSUE TITLE
Sketchs

### ISSUE THREAD

**Issue by Joanna-Victoria** [Rayaninha/AgroVen#5]
### Sketchs da Interface do Projeto

- [x] Sketch da Tela Inicial #10 
- [x] Sketch da Tela de Cadastro do Cliente #6
- [x] Sketch da Tela de Cadastro do Vendedor #7 
- [x] Sketch da Tela de Login #8 
- [x] Sketch da Tela "Esqueceu a Senha?" #9 
- [x] Sketch da Tela do Cliente #12 
- [x] Sketch do Postagem do Produto #13 
- [x] Sketch do da Tela de mensagens #16 
- [x] Sketch da Tela de Compras #14 
- [x] Sketch do Sobre #11
